name: something secret g

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:     # Allows manual triggering

jobs:
  generate-file:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Generate random filename and content
      id: generate
      run: |
        # Generate random number for filename
        RAND_NUM=$((RANDOM % 1000))
        FILENAME="random_code_file_$(date +'%Y%m%d')_${RAND_NUM}.cpp"
        
        # Create C++ content
        CONTENT="#include <iostream>
#include <cstdlib>
#include <ctime>

int main() {
    // Seed random number generator
    std::srand(std::time(0));
    
    // Generate random number between 1 and 100
    int random_num = 1 + (std::rand() % 100);
    
    std::cout << \"Random number: \" << random_num << std::endl;
    return 0;
}"

        # Set outputs for next steps
        echo "filename=$FILENAME" >> $GITHUB_OUTPUT
        echo "content<<EOF" >> $GITHUB_OUTPUT
        echo "$CONTENT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create and commit file
      run: |
        # Create the file with content
        echo "${{ steps.generate.outputs.content }}" > "${{ steps.generate.outputs.filename }}"
        
        # Configure git
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add, commit and push
        git add "${{ steps.generate.outputs.filename }}"
        git commit -m "Add daily random C++ file: ${{ steps.generate.outputs.filename }}"
        git push
