name: Notes Patch

on:
  schedule:
    - cron: '0 0 * * *'     # First run at 00:00 UTC
    - cron: '0 12 * * *'    # Second run at 12:00 UTC
  workflow_dispatch:        # Optional: allows manual trigger

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate C++ File
        run: |
          DATE=$(date +%F)
          TIME=$(date +%H%M)
          CODE=$(shuf -i 10000-99999 -n 1)
          FILENAME="${DATE}_${TIME}_${CODE}_file.cpp"
          echo "Generating file: $FILENAME"

          echo "#include <iostream>" > $FILENAME
          echo "int main() {" >> $FILENAME
          echo "    std::cout << $CODE << std::endl;" >> $FILENAME
          echo "    return 0;" >> $FILENAME
          echo "}" >> $FILENAME

      - name: Commit and Push as nikzad-avasam
        env:
          TOKEN: ${{ secrets.MY_GITHUB_PAT }}
        run: |
          git config user.name "nikzad-avasam"
          git config user.email "sam.nikzad90@gmail.com"
          git remote set-url origin https://$TOKEN@github.com/nikzad-avasam/sam-.git
          git add *.cpp
          git commit -m "new changes"
          git push
